{% set version = "2.6.0" %}

package:
  name: sphinx-sitemap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinx-sitemap/sphinx_sitemap-{{ version }}.tar.gz
  sha256: 5e0c66b9f2e371ede80c659866a9eaad337d46ab02802f9c7e5f7bc5893c28d2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - six
    - sphinx >=1.2

test:
  imports:
    - sphinx_sitemap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jdillard/sphinx-sitemap
  summary: Sitemap generator for Sphinx
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-sitemap.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
