{% set version = "2.7.1" %}

package:
  name: sphinx-sitemap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinx-sitemap/sphinx_sitemap-{{ version }}.tar.gz
  sha256: 28f02df7062e83628e9782a0d9449658a79c9813217c51db086edc51f20e7bd5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - six
    - sphinx >=1.2

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - sphinx_sitemap
  commands:
    - pip check

about:
  home: https://github.com/jdillard/sphinx-sitemap
  summary: Sitemap generator for Sphinx
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-sitemap.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
