{% set version = "2.6.0" %}

package:
  name: sphinx-sitemap
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx-sitemap/sphinx_sitemap-{{ version }}.tar.gz
  sha256: 984bef068bbdbc26cfae209a8b61392e9681abc9191b477cd30da406e3a60ee5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - six
    - sphinx >=1.2

test:
  imports:
    - sphinx_sitemap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jdillard/sphinx-sitemap
  summary: Sitemap generator for Sphinx
  license: MIT
  license_file: LICENSE
  doc_url: https://sphinx-sitemap.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
