# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.8.0"

package:
  name: sphinx-sitemap
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/s/sphinx-sitemap/sphinx_sitemap-${{ version }}.tar.gz
    sha256: 749d7184a0c7b73d486a232b54b5c1b38a0e2d6f18cf19fb1b033b8162b44a82

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - sphinx-last-updated-by-git

tests:
  - python:
      imports: sphinx_sitemap
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*

about:
  summary: Sitemap generator for Sphinx
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/jdillard/sphinx-sitemap
  documentation: https://sphinx-sitemap.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
